ci:
  autofix_commit_msg: pre-commit auto-fixes
  autofix_prs: true
  autoupdate_commit_msg: Update pre-commit hooks
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        types_or: [toml, yaml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        # Dependencies needed for their types.
        additional_dependencies: [nox, numpy, pytest]

  - repo: https://github.com/citation-file-format/cffconvert
    # As of 2026-03-06, the latest release tag is 2.0.0.
    # It does not include the pre-commit hook, causing `pre-commit autoupdate` to fail.
    # https://github.com/citation-file-format/cffconvert/issues/389#issuecomment-2480672136
    rev: b6045d78aac9e02b039703b030588d54d53262ac
    hooks:
      - id: validate-cff
